repos:
  - repo: local
    hooks:
      - id: zig-build
        name: "Zig Build"
        entry: zig build
        language: system
        always_run: true
        pass_filenames: false

      - id: zig-test
        name: "Zig Test"
        entry: zig test src/main.zig
        language: system
        always_run: true
        pass_filenames: false

      - id: zig-fmt
        name: "Zig Format"
        entry: zig fmt --check
        language: system
        types: [file]
        files: ^.*\.zig$
